#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Telegraph.Droid.Resource", IsApplication=true)]

namespace Telegraph.Droid
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "12.2.0.155")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7F010000
			public const int profile_title_array = 2130771968;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F020002
			public const int colorAccent = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int colorPrimary = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int colorPrimaryDark = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int colorPrimarySemiTransparent = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int launcher_background = 2130837510;
			
			// aapt resource value: 0x7F020000
			public const int ListViewHighlighted = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int ListViewSelected = 2130837505;
			
			// aapt resource value: 0x7F020007
			public const int navigationBarColor = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int roomActivityBackgroundColor = 2130837512;
			
			// aapt resource value: 0x7F020009
			public const int splashScreenBackground = 2130837513;
			
			// aapt resource value: 0x7F02000A
			public const int splash_background = 2130837514;
			
			// aapt resource value: 0x7F02000B
			public const int tabBarSelected = 2130837515;
			
			// aapt resource value: 0x7F02000C
			public const int tabBarUnselected = 2130837516;
			
			// aapt resource value: 0x7F02000D
			public const int textColorPrimary = 2130837517;
			
			// aapt resource value: 0x7F02000E
			public const int white = 2130837518;
			
			// aapt resource value: 0x7F02000F
			public const int windowBackground = 2130837519;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7F030000
			public const int activity_horizontal_margin = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int activity_vertical_margin = 2130903041;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F040001
			public const int call_receive = 2130968577;
			
			// aapt resource value: 0x7F040000
			public const int Company_logo = 2130968576;
			
			// aapt resource value: 0x7F040002
			public const int custom_cursor = 2130968578;
			
			// aapt resource value: 0x7F040003
			public const int delete = 2130968579;
			
			// aapt resource value: 0x7F040004
			public const int editor_cursor = 2130968580;
			
			// aapt resource value: 0x7F040005
			public const int ic_accept_call = 2130968581;
			
			// aapt resource value: 0x7F040006
			public const int ic_call_profile = 2130968582;
			
			// aapt resource value: 0x7F040007
			public const int ic_end_call = 2130968583;
			
			// aapt resource value: 0x7F040008
			public const int ic_new_addGroup_contact = 2130968584;
			
			// aapt resource value: 0x7F040009
			public const int ic_speaker_off = 2130968585;
			
			// aapt resource value: 0x7F04000A
			public const int ic_speaker_on = 2130968586;
			
			// aapt resource value: 0x7F04000B
			public const int ic_splash_screen1 = 2130968587;
			
			// aapt resource value: 0x7F04000C
			public const int ic_switch_camera = 2130968588;
			
			// aapt resource value: 0x7F04000D
			public const int ic_tab_call = 2130968589;
			
			// aapt resource value: 0x7F04000E
			public const int ic_tab_contact = 2130968590;
			
			// aapt resource value: 0x7F04000F
			public const int ic_tab_message = 2130968591;
			
			// aapt resource value: 0x7F040010
			public const int ic_tab_qr = 2130968592;
			
			// aapt resource value: 0x7F040011
			public const int ic_tab_setting = 2130968593;
			
			// aapt resource value: 0x7F040012
			public const int ic_turn_off_camera = 2130968594;
			
			// aapt resource value: 0x7F040013
			public const int ic_turn_off_mic = 2130968595;
			
			// aapt resource value: 0x7F040014
			public const int ic_turn_on_camera = 2130968596;
			
			// aapt resource value: 0x7F040015
			public const int ic_turn_on_mic = 2130968597;
			
			// aapt resource value: 0x7F040016
			public const int localview_round_corner = 2130968598;
			
			// aapt resource value: 0x7F040017
			public const int room_activity_bottom_bg = 2130968599;
			
			// aapt resource value: 0x7F04001B
			public const int roundedbg = 2130968603;
			
			// aapt resource value: 0x7F04001C
			public const int roundedbgdark = 2130968604;
			
			// aapt resource value: 0x7F040018
			public const int rounded_shadow_shape = 2130968600;
			
			// aapt resource value: 0x7F040019
			public const int rounded_video_shape = 2130968601;
			
			// aapt resource value: 0x7F04001A
			public const int rounded_video_shape_opaque = 2130968602;
			
			// aapt resource value: 0x7F04001D
			public const int splash_screen_activity = 2130968605;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F050000
			public const int accept = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int accept_lyt = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int activity_video_chat_view = 2131034114;
			
			// aapt resource value: 0x7F050003
			public const int avatar = 2131034115;
			
			// aapt resource value: 0x7F050004
			public const int bottomBar = 2131034116;
			
			// aapt resource value: 0x7F050005
			public const int bottomButtonsly = 2131034117;
			
			// aapt resource value: 0x7F050006
			public const int call_type = 2131034118;
			
			// aapt resource value: 0x7F050007
			public const int decline = 2131034119;
			
			// aapt resource value: 0x7F050008
			public const int decline_lyt = 2131034120;
			
			// aapt resource value: 0x7F050009
			public const int end_call_button = 2131034121;
			
			// aapt resource value: 0x7F05000A
			public const int local_video_container = 2131034122;
			
			// aapt resource value: 0x7F05000B
			public const int local_video_view_container = 2131034123;
			
			// aapt resource value: 0x7F05000C
			public const int main_container = 2131034124;
			
			// aapt resource value: 0x7F05000D
			public const int mute_audio_button = 2131034125;
			
			// aapt resource value: 0x7F05000E
			public const int mute_speaker = 2131034126;
			
			// aapt resource value: 0x7F05000F
			public const int mute_video_button = 2131034127;
			
			// aapt resource value: 0x7F050010
			public const int name = 2131034128;
			
			// aapt resource value: 0x7F050011
			public const int profile_image = 2131034129;
			
			// aapt resource value: 0x7F050012
			public const int remote_video_view_container = 2131034130;
			
			// aapt resource value: 0x7F050013
			public const int state = 2131034131;
			
			// aapt resource value: 0x7F050014
			public const int switch_cam_button = 2131034132;
			
			// aapt resource value: 0x7F050015
			public const int tv_incoming_call = 2131034133;
			
			// aapt resource value: 0x7F050016
			public const int username = 2131034134;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F060000
			public const int CallReceive = 2131099648;
			
			// aapt resource value: 0x7F060001
			public const int Room = 2131099649;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F070000
			public const int icon = 2131165184;
			
			// aapt resource value: 0x7F070001
			public const int icon_round = 2131165185;
			
			// aapt resource value: 0x7F070002
			public const int launcher_foreground = 2131165186;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7F080001
			public const int dialing = 2131230721;
			
			// aapt resource value: 0x7F080000
			public const int Rrrring = 2131230720;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F090000
			public const int app_name = 2131296256;
			
			// aapt resource value: 0x7F090001
			public const int default_notification_channel_id = 2131296257;
			
			// aapt resource value: 0x7F090002
			public const int join_button = 2131296258;
			
			// aapt resource value: 0x7F090003
			public const int join_description = 2131296259;
			
			// aapt resource value: 0x7F090004
			public const int permissions_not_granted = 2131296260;
			
			// aapt resource value: 0x7F090005
			public const int powered_by = 2131296261;
			
			// aapt resource value: 0x7F090006
			public const int profile_prompt = 2131296262;
			
			// aapt resource value: 0x7F090007
			public const int service_id = 2131296263;
			
			// aapt resource value: 0x7F090008
			public const int settings_bitrate = 2131296264;
			
			// aapt resource value: 0x7F090009
			public const int settings_framerate = 2131296265;
			
			// aapt resource value: 0x7F09000A
			public const int settings_name = 2131296266;
			
			// aapt resource value: 0x7F09000B
			public const int settings_profile = 2131296267;
			
			// aapt resource value: 0x7F09000C
			public const int settings_resolution = 2131296268;
			
			// aapt resource value: 0x7F09000D
			public const int settings_usemy = 2131296269;
			
			// aapt resource value: 0x7F09000E
			public const int splash_greetings = 2131296270;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F0A0000
			public const int AppCompatDialogStyle = 2131361792;
			
			// aapt resource value: 0x7F0A0001
			public const int AppStyle_Light = 2131361793;
			
			// aapt resource value: 0x7F0A0002
			public const int DT_ActionBar = 2131361794;
			
			// aapt resource value: 0x7F0A0003
			public const int DT_Theme = 2131361795;
			
			// aapt resource value: 0x7F0A0004
			public const int DT_Theme_Base = 2131361796;
			
			// aapt resource value: 0x7F0A0005
			public const int DT_Theme_Room = 2131361797;
			
			// aapt resource value: 0x7F0A0006
			public const int MainTheme = 2131361798;
			
			// aapt resource value: 0x7F0A0007
			public const int MainTheme_Base = 2131361799;
			
			// aapt resource value: 0x7F0A0008
			public const int MyTextAppearance_Material_Button = 2131361800;
			
			// aapt resource value: 0x7F0A0009
			public const int Theme_CallReceive = 2131361801;
			
			// aapt resource value: 0x7F0A000A
			public const int Theme_Splash = 2131361802;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7F0B0000
			public const int file_paths = 2131427328;
			
			// aapt resource value: 0x7F0B0001
			public const int network_security_config = 2131427329;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
