// This file has been autogenerated from a class added in the UI designer.

using System;
using UIKit;

namespace Telegraph.iOS
{
	public partial class SettingsViewController : UIViewController
	{
		public SettingsViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
