// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Telegraph.iOS
{
	public partial class JoinViewController : UIViewController
	{
		public JoinViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
